
select*
from sales_data;

----------------------------------------------------------------------------------
-- What is the total revenue generated by each gender?
----------------------------------------------------------------------------------
SELECT 
    customer_gender,
    SUM(net_sales) AS total_revenue
FROM sales_data
GROUP BY customer_gender;


----------------------------------------------------------------------------------
-- Which customers received discounts but still spent above average?
----------------------------------------------------------------------------------
SELECT 
    sales_id,
    net_sales,
    discount
FROM sales_data
WHERE discount > 0
AND net_sales > (
    SELECT AVG(net_sales) FROM sales_data
)LIMIT 10;


----------------------------------------------------------------------------------
-- Which product categories generate the highest average profit?
----------------------------------------------------------------------------------
SELECT 
    product_category,
    AVG(profit) AS avg_profit
FROM sales_data
GROUP BY product_category
ORDER BY avg_profit DESC
LIMIT 10;


----------------------------------------------------------------------------------
-- Compare average spending across age groups
----------------------------------------------------------------------------------
SELECT 
    age_group,
    AVG(net_sales) AS avg_spending,
    SUM(net_sales) AS total_revenue
FROM sales_data
GROUP BY age_group;


----------------------------------------------------------------------------------
-- Do high discounts actually increase revenue?
----------------------------------------------------------------------------------
SELECT 
    discount_level,
    COUNT(*) AS total_orders,
    AVG(net_sales) AS avg_sales,
    SUM(net_sales) AS total_revenue
FROM sales_data
GROUP BY discount_level;


----------------------------------------------------------------------------------
-- Which product categories have the highest % of discounted sales?
----------------------------------------------------------------------------------
SELECT 
    product_category,
    COUNT(CASE WHEN discount > 0 THEN 1 END) * 100.0 / COUNT(*) AS discount_percentage
FROM sales_data
GROUP BY product_category
ORDER BY discount_percentage DESC
limit 10;


----------------------------------------------------------------------------------
-- Segment customers (Young, Adult, Senior) and count them
----------------------------------------------------------------------------------
SELECT 
    age_group,
    COUNT(*) AS total_customers
FROM sales_data
GROUP BY age_group;


----------------------------------------------------------------------------------
-- Top 3 products (categories) by sales within each region
----------------------------------------------------------------------------------
SELECT *
FROM (
    SELECT 
        sales_region,
        product_category,
        SUM(net_sales) AS total_sales,
        RANK() OVER (PARTITION BY sales_region ORDER BY SUM(net_sales) DESC) AS rnk
    FROM sales_data
    GROUP BY sales_region, product_category
) ranked
WHERE rnk <= 3;


----------------------------------------------------------------------------------
-- Are high-value customers concentrated in certain age groups?
----------------------------------------------------------------------------------
SELECT 
    age_group,
    AVG(customer_value) AS avg_customer_value
FROM sales_data
GROUP BY age_group
ORDER BY avg_customer_value DESC;


----------------------------------------------------------------------------------
-- Revenue contribution of each age group
----------------------------------------------------------------------------------
SELECT 
    age_group,
    SUM(net_sales) AS total_revenue,
    ROUND(SUM(net_sales) * 100 / SUM(SUM(net_sales)) OVER (), 2) AS contribution_pct
FROM sales_data
GROUP BY age_group;


----------------------------------------------------------------------------------
--  Which sales reps consistently perform above average?
----------------------------------------------------------------------------------
SELECT 
    sales_representative,
    AVG(net_sales) AS avg_sales
FROM sales_data
GROUP BY sales_representative
HAVING AVG(net_sales) > (
    SELECT AVG(net_sales) FROM sales_data
)
ORDER BY avg_sales DESC
LIMIT 10;


----------------------------------------------------------------------------------
-- Which months generate the highest revenue?
----------------------------------------------------------------------------------
SELECT 
    month,
    SUM(net_sales) AS total_revenue
FROM sales_data
GROUP BY month
ORDER BY total_revenue DESC;



----------------------------------------------------------------------------------
 -- Which regions are underperforming?
----------------------------------------------------------------------------------
SELECT 
    sales_region,
    SUM(net_sales) AS total_sales
FROM sales_data
GROUP BY sales_region
HAVING total_sales < (
    SELECT AVG(region_sales)
    FROM (
        SELECT SUM(net_sales) AS region_sales
        FROM sales_data
        GROUP BY sales_region
    ) t
)LIMIT 10;

